[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "128h"

[".config/wallpaper"]
type = "git-repo"
url = "https://github.com/sequoiasnow/wallpaper.git"
refreshPeriod = "256h"
