brew "bash"
brew "chezmoi"
brew "ghcup"
brew "git"
brew "helix"
brew "neofetch"
brew "pipes-sh"
brew "postgresql@18", link: true
brew "starship"
brew "tmux"
brew "zsh"
cask "font-monaspice-nerd-font"
cask "spotify"
cask "wezterm"
