set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal "xterm-256color"

set -s escape-time 0

# Windowing options
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Allow quick reload
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Window management
bind c new-window -c '#{pane_current_path}'

# act like emacs
set-option -g status-keys emacs

# act like vim
setw -g mode-keys vi

unbind-key -T copy-mode-vi v

bind-key -T copy-mode-vi v \
  send-keys -X begin-selection

bind-key -T copy-mode-vi 'C-v' \
  send-keys -X rectangle-toggle

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @tmux2k-theme 'duo'

# to show icons only
set -g @tmux2k-icons-only true

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin '2kabhishek/tmux2k'
set -g status-position top


unbind r
bind r source-file ~/.config/tmux/tmux.conf


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
